name: tests ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mandatory tests
      run: cd push_swap; make; ./push_swap 1 2 3 4 5;
      shell: bash
